
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/WezTerm/"
      - "C:/Program Files/Neovim/bin/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files (x86)/Lua/5.1/"
      - "C:/Program Files (x86)/Lua/5.1/clibs/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/LLVM/bin/"
      - "C:/Program Files (x86)/LLVM/bin/"
      - "C:/Program Files/starship/bin/"
      - "C:/Program Files/PowerShell/7/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/ProgramData/mingw64/mingw64/bin/"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/"
    searched_directories:
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/WezTerm/ninja-build.com"
      - "C:/Program Files/WezTerm/ninja-build.exe"
      - "C:/Program Files/WezTerm/ninja-build"
      - "C:/Program Files/WezTerm/ninja.com"
      - "C:/Program Files/WezTerm/ninja.exe"
      - "C:/Program Files/WezTerm/ninja"
      - "C:/Program Files/WezTerm/samu.com"
      - "C:/Program Files/WezTerm/samu.exe"
      - "C:/Program Files/WezTerm/samu"
      - "C:/Program Files/Neovim/bin/ninja-build.com"
      - "C:/Program Files/Neovim/bin/ninja-build.exe"
      - "C:/Program Files/Neovim/bin/ninja-build"
      - "C:/Program Files/Neovim/bin/ninja.com"
      - "C:/Program Files/Neovim/bin/ninja.exe"
      - "C:/Program Files/Neovim/bin/ninja"
      - "C:/Program Files/Neovim/bin/samu.com"
      - "C:/Program Files/Neovim/bin/samu.exe"
      - "C:/Program Files/Neovim/bin/samu"
      - "C:/ProgramData/chocolatey/bin/ninja-build.com"
      - "C:/ProgramData/chocolatey/bin/ninja-build.exe"
      - "C:/ProgramData/chocolatey/bin/ninja-build"
      - "C:/ProgramData/chocolatey/bin/ninja.com"
      - "C:/ProgramData/chocolatey/bin/ninja.exe"
      - "C:/ProgramData/chocolatey/bin/ninja"
      - "C:/ProgramData/chocolatey/bin/samu.com"
      - "C:/ProgramData/chocolatey/bin/samu.exe"
      - "C:/ProgramData/chocolatey/bin/samu"
      - "C:/Program Files (x86)/Lua/5.1/ninja-build.com"
      - "C:/Program Files (x86)/Lua/5.1/ninja-build.exe"
      - "C:/Program Files (x86)/Lua/5.1/ninja-build"
      - "C:/Program Files (x86)/Lua/5.1/ninja.com"
      - "C:/Program Files (x86)/Lua/5.1/ninja.exe"
      - "C:/Program Files (x86)/Lua/5.1/ninja"
      - "C:/Program Files (x86)/Lua/5.1/samu.com"
      - "C:/Program Files (x86)/Lua/5.1/samu.exe"
      - "C:/Program Files (x86)/Lua/5.1/samu"
      - "C:/Program Files (x86)/Lua/5.1/clibs/ninja-build.com"
      - "C:/Program Files (x86)/Lua/5.1/clibs/ninja-build.exe"
      - "C:/Program Files (x86)/Lua/5.1/clibs/ninja-build"
      - "C:/Program Files (x86)/Lua/5.1/clibs/ninja.com"
      - "C:/Program Files (x86)/Lua/5.1/clibs/ninja.exe"
      - "C:/Program Files (x86)/Lua/5.1/clibs/ninja"
      - "C:/Program Files (x86)/Lua/5.1/clibs/samu.com"
      - "C:/Program Files (x86)/Lua/5.1/clibs/samu.exe"
      - "C:/Program Files (x86)/Lua/5.1/clibs/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Program Files/LLVM/bin/ninja-build.com"
      - "C:/Program Files/LLVM/bin/ninja-build.exe"
      - "C:/Program Files/LLVM/bin/ninja-build"
      - "C:/Program Files/LLVM/bin/ninja.com"
      - "C:/Program Files/LLVM/bin/ninja.exe"
      - "C:/Program Files/LLVM/bin/ninja"
      - "C:/Program Files/LLVM/bin/samu.com"
      - "C:/Program Files/LLVM/bin/samu.exe"
      - "C:/Program Files/LLVM/bin/samu"
      - "C:/Program Files (x86)/LLVM/bin/ninja-build.com"
      - "C:/Program Files (x86)/LLVM/bin/ninja-build.exe"
      - "C:/Program Files (x86)/LLVM/bin/ninja-build"
      - "C:/Program Files (x86)/LLVM/bin/ninja.com"
      - "C:/Program Files (x86)/LLVM/bin/ninja.exe"
      - "C:/Program Files (x86)/LLVM/bin/ninja"
      - "C:/Program Files (x86)/LLVM/bin/samu.com"
      - "C:/Program Files (x86)/LLVM/bin/samu.exe"
      - "C:/Program Files (x86)/LLVM/bin/samu"
      - "C:/Program Files/starship/bin/ninja-build.com"
      - "C:/Program Files/starship/bin/ninja-build.exe"
      - "C:/Program Files/starship/bin/ninja-build"
      - "C:/Program Files/starship/bin/ninja.com"
      - "C:/Program Files/starship/bin/ninja.exe"
      - "C:/Program Files/starship/bin/ninja"
      - "C:/Program Files/starship/bin/samu.com"
      - "C:/Program Files/starship/bin/samu.exe"
      - "C:/Program Files/starship/bin/samu"
      - "C:/Program Files/PowerShell/7/ninja-build.com"
      - "C:/Program Files/PowerShell/7/ninja-build.exe"
      - "C:/Program Files/PowerShell/7/ninja-build"
      - "C:/Program Files/PowerShell/7/ninja.com"
      - "C:/Program Files/PowerShell/7/ninja.exe"
      - "C:/Program Files/PowerShell/7/ninja"
      - "C:/Program Files/PowerShell/7/samu.com"
      - "C:/Program Files/PowerShell/7/samu.exe"
      - "C:/Program Files/PowerShell/7/samu"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja-build.com"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja-build.exe"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja-build"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja.com"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja.exe"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja"
      - "C:/ProgramData/mingw64/mingw64/bin/samu.com"
      - "C:/ProgramData/mingw64/mingw64/bin/samu.exe"
      - "C:/ProgramData/mingw64/mingw64/bin/samu"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/1650s/AppData/Local/Microsoft/WindowsApps/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\WezTerm"
        - "C:\\Program Files\\Neovim\\bin"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files (x86)\\Lua\\5.1"
        - "C:\\Program Files (x86)\\Lua\\5.1\\clibs"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\LLVM\\bin"
        - "C:\\Program Files (x86)\\LLVM\\bin"
        - "C:\\Program Files\\starship\\bin\\"
        - "C:\\Program Files\\PowerShell\\7\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\ProgramData\\mingw64\\mingw64\\bin"
        - "C:\\Users\\1650s\\AppData\\Local\\Microsoft\\WindowsApps"
...
